name: Release Java API to Maven Central

on:
  release:
    types:
      - published

jobs:
  java-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew ./.github/scripts/*.sh
      - name: Write gradle.properties
        run: |
          mkdir -p ~/.gradle
          echo "${{ secrets.GRADLE_PROPERTIES }}" | base64 -d > ~/.gradle/gradle.properties
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --pinentry-mode loopback --passphrase "${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}" --export-secret-key ${{ secrets.OSSRH_GPG_KEY_ID }} > ~/.gradle/maven-central.gpg
          gpg --list-secret-keys --keyid-format LONG
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh $(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
      - name: Build and Publish
        working-directory: .
        env:
          SIGNING_KEY_ID: ${{ secrets.OSSRH_GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ~/.gradle/maven-central.gpg
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          ./gradlew setVersion -P version=$(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
          ./gradlew build test publish --info --stacktrace
